[package]
name = "codeviz-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = "1.0.151"
codeviz-mcp = { path = "../codeviz-mcp" }
codeviz-core = { path = "../codeviz-core" }
codeviz-python = { path = "../codeviz-python" }
codeviz-typescript = { version = "0.1.0", path = "../codeviz-typescript" }
codeviz-go = { version = "0.1.0", path = "../codeviz-go" }
